on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip artifact for deployment
        run: zip release-${{ github.ref_name }}.zip ./build/me.reinii.harvest-billables.sdPlugin -r

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release-${{ github.ref_name }}.zip
          release_name: Release ${{ github.ref_name }}
          fail_on_unmatched_files: true
          draft: true
