on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: StreamDeck Distribution Tool
        uses: AdamCarballo/streamdeck-distribution-tool@v1
        with:
          input: build/me.reinii.harvest-billables.sdPlugin
          output: build

      - name: Zip plugin
        run: |
          zip -j "Harvest Billables for Stream Deck ${{ github.ref_name }}.zip" build/me.reinii.harvest-billables.streamDeckPlugin
          (cd build && zip -r ../build-${{ github.ref_name }}.zip .)

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "Harvest Billables for Stream Deck ${{ github.ref_name }}.zip"
            build-${{ github.ref_name }}.zip
          fail_on_unmatched_files: true
          draft: true
