on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip plugin
        run: (cd build && zip -r ../release-${{ github.ref_name }}.zip .)

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release-${{ github.ref_name }}.zip
          fail_on_unmatched_files: true
          draft: true
